name: Deploy All Services to EC2 (PR -> main)

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-front:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image for frontend
      run: |
        docker build -t sebitas11/my-react-app ./FrontEnd

    - name: Push frontend image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push sebitas11/my-react-app:latest

    - name: Deploy Frontend to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 44.195.234.109
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEYP }}
        script: |
          docker stop my-react-app || true
          docker rm my-react-app || true
          docker pull sebitas11/my-react-app
          docker run -d --name my-react-app -p 80:80 --restart unless-stopped sebitas11/my-react-app

  deploy-auth:
    name: Deploy Auth Services
    runs-on: ubuntu-latest
    needs: deploy-front

    steps:
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Auth images
      run: |
        docker build -t sebitas11/login-service ./BackEnd/Authentication-Domain/Login
        docker build -t sebitas11/register-service ./BackEnd/Authentication-Domain/Register
        docker build -t sebitas11/captcha ./BackEnd/Authentication-Domain/captcha-microservice

    - name: Push Auth images
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push sebitas11/login-service:latest
        docker push sebitas11/register-service:latest
        docker push sebitas11/captcha:latest

    - name: Deploy Auth services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 44.199.55.78
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEYP }}
        script: |
          docker stop login-service || true
          docker rm login-service || true
          docker stop register-service || true
          docker rm register-service || true
          docker stop captcha || true
          docker rm captcha || true

          docker pull sebitas11/login-service
          docker pull sebitas11/register-service
          docker pull sebitas11/captcha

          docker run -d --name login-service -p 8001:8001 --restart unless-stopped sebitas11/login-service
          docker run -d --name register-service -p 8002:8002 --restart unless-stopped sebitas11/register-service
          docker run -d --name captcha -p 5000:5000 --restart unless-stopped sebitas11/captcha

  deploy-user:
    name: Deploy User Services
    runs-on: ubuntu-latest
    needs: deploy-auth

    steps:
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build User images
      run: |
        docker build -t sebitas11/change-password ./BackEnd/User-Domain/change-password
        docker build -t sebitas11/update-username ./BackEnd/User-Domain/update-username
        docker build -t sebitas11/delete-account ./BackEnd/User-Domain/delete-user
        docker build -t sebitas11/time ./BackEnd/User-Domain/date-time-service

    - name: Push User images
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push sebitas11/change-password:latest
        docker push sebitas11/update-username:latest
        docker push sebitas11/delete-account:latest
        docker push sebitas11/time

    - name: Deploy User services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 34.202.200.186
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEYP }}
        script: |
          docker stop change-password || true
          docker rm change-password || true
          docker stop update-username || true
          docker rm update-username || true
          docker stop delete-account || true
          docker rm delete-account || true
          docker stop time || true
          docker rm time || true

          docker pull sebitas11/change-password
          docker pull sebitas11/update-username
          docker pull sebitas11/delete-account
          docker pull sebitas11/time

          docker run -d --name change-password -p 8005:8005 --restart unless-stopped sebitas11/change-password
          docker run -d --name update-username -p 8003:8003 --restart unless-stopped sebitas11/update-username
          docker run -d --name delete-account -p 8004:8004 --restart unless-stopped sebitas11/delete-account
          docker run -d --name time -p 8000:8000 --restart unless-stopped sebitas11/time

  deploy-reservation:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEYP }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for add and get friends services
      run: |
        docker build -t sebitas11/dating ./BackEnd/Reservation-Domain/dating_service
        docker build -t sebitas11/get-dating ./BackEnd/Reservation-Domain/get_dating

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push sebitas11/dating
        docker push sebitas11/get-dating

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 98.89.253.33
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEYP }}
        script: |
          # stop
          docker stop dating || true
          docker rm dating || true
          docker stop get-dating || true
          docker rm get-dating || true

          # Download
          docker pull sebitas11/dating
          docker pull sebitas11/get-dating

          # Ejecute
          docker run -d --name dating -p 8001:8001 --restart unless-stopped sebitas11/dating
          docker run -d --name get-dating -p 8002:8002 --restart unless-stopped sebitas11/get-dating