name: Deploy User Service to EC2

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images services
      run: |
        docker build -t sebitas11/change-password ./User-Domain/change-password
        docker build -t sebitas11/update-username ./User-Domain/update-username
        docker build -t sebitas11/delete-account ./User-Domain/delete-user
        docker build -t sebitas11/time ./User-Domain/date-time-service


    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push sebitas11/change-password
        docker push sebitas11/update-username
        docker push sebitas11/delete-account
        docker push sebitas11/time

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 3.227.167.247
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Docker
          docker stop change-password || true
          docker rm change-password || true
          docker stop update-username || true
          docker rm update-username || true
          docker stop delete-account || true
          docker rm delete-account || true
          docker stop time || true
          docker rm time || true

          # D
          docker pull sebitas11/change-password
          docker pull sebitas11/update-username
          docker pull sebitas11/delete-account
          docker pull sebitas11/time

          # E
          docker run -d --name change-password -p 8005:8005 --restart unless-stopped sebitas11/change-password
          docker run -d --name update-username -p 8003:8003 --restart unless-stopped sebitas11/update-username
          docker run -d --name delete-account -p 8004:8004 --restart unless-stopped sebitas11/delete-account
          docker run -d --name time -p 8000:8000 --restart unless-stopped sebitas11/time